#ifndef NUMERIC_HPP
#define NUMERIC_HPP

#include <string>

namespace IRC {

enum Numeric {
  // NOT OFFICIAL IRC NUMERIC REPLY BUT TO INDICATE DO NOT SEND ANY MESSAGE
  DO_NOTHING = -1,
  RPL_STRREPLY = -2,
  ERR_REGISTERBEFOREPASS = -3,

  // Success replies
  RPL_WELCOME = 1,
  RPL_YOURHOST = 2,
  RPL_CREATED = 3,
  RPL_MYINFO = 4,
  RPL_UMODEIS = 221,
  RPL_CHANNELMODEIS = 324,
  RPL_UNIQOPIS = 325,
  RPL_NOTOPIC = 331,
  RPL_TOPIC = 332,
  RPL_INVITING = 341,
  RPL_INVITELIST = 346,
  RPL_ENDOFINVITELIST = 347,
  RPL_EXCEPTLIST = 348,
  RPL_ENDOFEXCEPTLIST = 349,
  RPL_NAMREPLY = 353,
  RPL_ENDOFNAMES = 366,
  RPL_BANLIST = 367,
  RPL_ENDOFBANLIST = 368,
  RPL_YOUREOPER = 381,
  RPL_YOURESERVICE = 383,

  // Error replies
  ERR_NOSUCHNICK = 401,
  ERR_NOSUCHCHANNEL = 403,
  ERR_TOOMANYCHANNELS = 405,
  ERR_TOOMANYTARGETS = 407,
  ERR_NORECIPIENT = 411,
  ERR_NOTEXTTOSEND = 412,
  ERR_UNKNOWNCOMMAND = 421,
  ERR_NONICKNAMEGIVEN = 431,
  ERR_ERRONEUSNICKNAME = 432,
  ERR_NICKNAMEINUSE = 433,
  ERR_NICKCOLLISION = 436,
  ERR_UNAVAILRESOURCE = 437,
  ERR_USERNOTINCHANNEL = 441,
  ERR_NOTONCHANNEL = 442,
  ERR_USERONCHANNEL = 443,
  ERR_NOTREGISTERED = 451,
  ERR_NEEDMOREPARAMS = 461,
  ERR_ALREADYREGISTRED = 462,
  ERR_PASSWDMISMATCH = 464,
  ERR_KEYSET = 467,
  ERR_CHANNELISFULL = 471,
  ERR_INVITEONLYCHAN = 473,
  ERR_BANNEDFROMCHAN = 474,
  ERR_BADCHANNELKEY = 475,
  ERR_BADCHANMASK = 476,
  ERR_NOCHANMODES = 477,
  ERR_CHANOPRIVSNEEDED = 482,
  ERR_RESTRICTED = 484,
  ERR_NOOPERHOST = 491,
  ERR_UMODEUNKNOWNFLAG = 501,
  ERR_USERSDONTMATCH = 502,

  // Placeholder for non-standard or unassigned error
  ERR_TOOMANYMATCHES =
      999  // Does not exist on RFC 2812, assigned a high number
};

// Convert IRC::Numeric enum to string code (e.g., RPL_WELCOME -> "001")
// Returns "000" for unknown numeric codes
std::string numericToCode(Numeric numeric);

}  // namespace IRC

#endif